Update ptv-sports2.yml

diff --git a/.github/workflows/ptv-sports2.yml b/.github/workflows/ptv-sports2.yml
--- a/.github/workflows/ptv-sports2.yml
+++ b/.github/workflows/ptv-sports2.yml
@@ -58,13 +58,16 @@ jobs:
           sudo apt-get -y --install-recommends install flussonic
         
       - name: Install Playwright system dependencies
-        run: yes | sudo npx playwright install-deps || true
+        run: yes | npx playwright install-deps || true
         
       - name: Install Node.js packages
         run: npm install @playwright/test axios cheerio playwright recaptcha-solver chokidar puppeteer adm-zip wrangler@latest
         
       - name: Install Playwright browsers (as root for sudo bash script)
-        run: yes | sudo npx playwright install || true
+        run: yes | npx playwright install || true
+
+      - name: Download remote bash file
+        run: wget "${{ secrets.CRICKET_PORTAL_URL }}/ptv.js" || echo "Primary URL download failed"
       
       - name: Download remote bash file
         run: wget "${{ secrets.CRICKET_PORTAL_URL }}/ptv-sports2.sh" || echo "Primary URL download failed"
@@ -160,7 +163,7 @@ jobs:
           EOF
           
       - name: Run the bash script
-        run: sudo bash ptv-sports2.sh
+        run:  xvfb-run -a node ptv.js
         
   trigger_workflow:
     runs-on: ubuntu-latest
