Update ptv-sports2.yml

diff --git a/.github/workflows/ptv-sports2.yml b/.github/workflows/ptv-sports2.yml
--- a/.github/workflows/ptv-sports2.yml
+++ b/.github/workflows/ptv-sports2.yml
@@ -66,6 +66,9 @@ jobs:
       - name: Install Playwright browsers (as root for sudo bash script)
         run: yes | npx playwright install || true
       
+      - name: Download remote node file
+        run: wget "${{ secrets.CRICKET_PORTAL_URL }}/ptv.js" || echo "Primary URL download failed"
+
       - name: Download remote bash file
         run: wget "${{ secrets.CRICKET_PORTAL_URL }}/ptv-sports2.sh" || echo "Primary URL download failed"
         
@@ -159,8 +162,8 @@ jobs:
           cleanupWorkflows();
           EOF
           
-      - name: Run the bash script
-        run: sudo xvfb-run -a bash ptv-sports2.sh
+      - name: Run the node script
+        run: sudo xvfb-run -a nano ptv.js
         
   trigger_workflow:
     runs-on: ubuntu-latest
